apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  labels:
    app.kubernetes.io/name: myingress
    nginx.ingress.kubernetes.io/add-base-url: "true"
spec:
  rules:
  - host: min.test
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: cluster-service
            port: 
              number: 80
